id: probe_expedition
namespace: company.team

inputs:
  - id: domain
    type: STRING
    defaults: ""

tasks:
  - id: parent
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
    - id: seq1
      type: io.kestra.plugin.core.flow.Sequential
      tasks:
      - id: expedition1
        type: io.kestra.plugin.core.flow.Subflow
        namespace: company.team
        flowId: expedition
        wait: true
        inputs:
          search_term: 'grant site:{{inputs.domain}}'

      - id: extract_domains1
        type: io.kestra.plugin.core.flow.Subflow
        namespace: company.team
        flowId: domain_extraction
        wait: true
        inputs:
          url_list: "{{outputs.expedition1.outputs.link_list}}"
          
    - id: seq2
      type: io.kestra.plugin.core.flow.Sequential
      tasks:
        - id: expedition2
          type: io.kestra.plugin.core.flow.Subflow
          namespace: company.team
          flowId: expedition
          wait: true
          inputs:
            search_term: 'grant related:{{inputs.domain}}'

        - id: extract_domains2
          type: io.kestra.plugin.core.flow.Subflow
          namespace: company.team
          flowId: domain_extraction
          wait: true
          inputs:
            url_list: "{{outputs.expedition2.outputs.link_list}}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: probe